### ISSUE TITLE
inter-subject for validation model

### ISSUE THREAD

**Issue by smnfouladi** [levchenkoegor/Inter-Subject_Correlation#1]
i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work?

**Comment by levchenkoegor** [comment]
> i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work?

Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for [EEG data](https://en.wikipedia.org/wiki/Electroencephalography) and haven't been tested on any other type of the data. The main idea of the method is described very well in the [article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3353265/). To perform calculations you can use just two functions from `ISC.py` file: `train_cca` and `apply_cca` on your data in dictionary format.

I am happy to help you, but please describe your issue in more details

**Comment by smnfouladi** [comment]
Hithank you for answering.i have a model to train eeg data from 189 case and classify  them to 3 class alzheimer,mci and control person.after train and evaluate my model,i want to put away some of my data and re-train model without them ,then feed the omitted data to the model for predict their class.for example alzheimer or mci or control.
 I want to know more about how this works.How to check the omitted data? in the training or classification phase?untagged or tagged?




    On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor <notifications@github.com> wrote:  
 
 

i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work?


Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format.

I am happy to help you, but please describe your issue in more details

**Comment by smnfouladi** [comment]
hii solve my problem .but now I have another problem.model accuracy is 46% .I changed a lot of parameters,complex model and... but accuracy  didn't change.in data matrix ,there are negative numbers.i attach a sample of data.Could this be due to the data type?please help me.

    On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor <notifications@github.com> wrote:  
 
 

i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work?


Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format.

I am happy to help you, but please describe your issue in more details

**Comment by levchenkoegor** [comment]
> hii solve my problem .but now I have another problem.model accuracy is 46% .I changed a lot of parameters,complex model and... but accuracy  didn't change.in data matrix ,there are negative numbers.i attach a sample of data.Could this be due to the data type?please help me. On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor <notifications@github.com> wrote: i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work? Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format. I am happy to help you, but please describe your issue in more details — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry, can't see any attachment. Can you try to attach the sample of the data again?

**Comment by smnfouladi** [comment]
hi
yes.i attach again

    On Tuesday, December 24, 2019, 5:43:47 PM GMT+3:30, Egor <notifications@github.com> wrote:  
 
 

hii solve my problem .but now I have another problem.model accuracy is 46% .I changed a lot of parameters,complex model and... but accuracy  didn't change.in data matrix ,there are negative numbers.i attach a sample of data.Could this be due to the data type?please help me. On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor notifications@github.com wrote: i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work? Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format. I am happy to help you, but please describe your issue in more details — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Sorry, can't see any attachment. Can you try to attach the sample of the data again?

**Comment by levchenkoegor** [comment]
> hi yes.i attach again On Tuesday, December 24, 2019, 5:43:47 PM GMT+3:30, Egor <notifications@github.com> wrote: hii solve my problem .but now I have another problem.model accuracy is 46% .I changed a lot of parameters,complex model and... but accuracy  didn't change.in data matrix ,there are negative numbers.i attach a sample of data.Could this be due to the data type?please help me. On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor notifications@github.com wrote: i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work? Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format. I am happy to help you, but please describe your issue in more details — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Sorry, can't see any attachment. Can you try to attach the sample of the data again? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry, still nothing

**Comment by smnfouladi** [comment]
hi
i attach again. Below is the code link :
Please see code

In the classification of the 3classes, the accuracy is not more than 0.46 · Issue #353 · boncey/Flickr4Java

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
In the classification of the 3classes, the accuracy is not more than 0.4...

i have a network for classify data into 3 class.data are 13760 Two-dimensional array with 19 row and 1280 column...
 |

 |

 |




 

    On Sunday, December 29, 2019, 9:20:55 PM GMT+3:30, Egor <notifications@github.com> wrote:  
 
 

hi yes.i attach again On Tuesday, December 24, 2019, 5:43:47 PM GMT+3:30, Egor notifications@github.com wrote: hii solve my problem .but now I have another problem.model accuracy is 46% .I changed a lot of parameters,complex model and... but accuracy  didn't change.in data matrix ,there are negative numbers.i attach a sample of data.Could this be due to the data type?please help me. On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor notifications@github.com wrote: i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work? Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format. I am happy to help you, but please describe your issue in more details — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Sorry, can't see any attachment. Can you try to attach the sample of the data again? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Sorry, still nothing

**Comment by smnfouladi** [comment]
hi
below is colab link of my code: https://colab.research.google.com/drive/1fBKSwFTUCXkp3NzxvdYdtOVBd1fiDvvf#scrollTo=nBDugm_JWSab

    On Sunday, December 29, 2019, 9:26:23 PM GMT+3:30, saman fouladi <smnfouladi@yahoo.com> wrote:  
 
  hi
i attach again. Below is the code link :
Please see code

In the classification of the 3classes, the accuracy is not more than 0.46 · Issue #353 · boncey/Flickr4Java

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
In the classification of the 3classes, the accuracy is not more than 0.4...

i have a network for classify data into 3 class.data are 13760 Two-dimensional array with 19 row and 1280 column...
 |

 |

 |




 

    On Sunday, December 29, 2019, 9:20:55 PM GMT+3:30, Egor <notifications@github.com> wrote:  
 
 

hi yes.i attach again On Tuesday, December 24, 2019, 5:43:47 PM GMT+3:30, Egor notifications@github.com wrote: hii solve my problem .but now I have another problem.model accuracy is 46% .I changed a lot of parameters,complex model and... but accuracy  didn't change.in data matrix ,there are negative numbers.i attach a sample of data.Could this be due to the data type?please help me. On Thursday, December 19, 2019, 4:42:03 PM GMT+3:30, Egor notifications@github.com wrote: i have a deep learning model and i train my data and evaluate model by accuracy,smv,knn ,....i want use inter-subject for evaluate model by keras python.please guide me for this algorithm and code.How does this algorithm work? Hi, can you please describe for what exactly you want to use ISC method? The algorithm is working for EEG data and haven't been tested on any other type of the data. The main idea of the method is described very well in the article. To perform calculations you can use just two functions from ISC.py file: train_cca and apply_cca on your data in dictionary format. I am happy to help you, but please describe your issue in more details — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Sorry, can't see any attachment. Can you try to attach the sample of the data again? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Sorry, still nothing
